data: 
  name: s-nlp/TextGraphs17-shared-task-dataset
  max_length: 128

seed: 42

model: 
  name: bert-base-uncased
  text_embedding_dim: 768
  hidden_dim: 256
  num_layers: 3

train:
  epochs: 100
  batch_size: 16384
  learning_rate: 0.00001
  weight_decay: 0.01