data: 
  name: s-nlp/TextGraphs17-shared-task-dataset
  max_length: 128

seed: 42

model: 
  name: bert-large-cased
  text_embedding_dim: 1024
  hidden_dim: 256
  num_layers: 3
  freeze_transformer: True

train:
  epochs: 100
  batch_size: 32768
  learning_rate: 0.00001
  weight_decay: 0.01
  save_path: default2